_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 49
                - 53
                - 55
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 49
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.4
            "5": 0.19.11
            "6": 4.51.2
            "8":
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
batch_size:
    value: 16
bert_model:
    value: bert-base-uncased
dropout:
    value: 0.1
embed_dim:
    value: 128
epochs:
    value: 3
file_path:
    value: ../dataset/Dataset-Research.csv
kernel_sizes:
    value:
        - 3
        - 4
        - 5
lr:
    value: 0.001
max_length:
    value: 128
n_folds:
    value: 2
num_classes:
    value: 2
num_filters:
    value: 100
output_dir:
    value: model_outputs
output_model:
    value: false
seed:
    value: 29082002
tokenizer:
    value: indobenchmark/indobert-base-p1
use_wandb:
    value: true
vocab_size:
    value: 40000
